// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1C7gLtkHMlJGSiT47UaipAIFTGfU7uc',
    appId: '1:986887862089:web:fa7a5143e567bf0f264c98',
    messagingSenderId: '986887862089',
    projectId: 'let-s-cook-880bc',
    authDomain: 'let-s-cook-880bc.firebaseapp.com',
    storageBucket: 'let-s-cook-880bc.appspot.com',
    measurementId: 'G-RQYDZR2HJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfVIdrZaHNEMFU8LazBv2w1gKaVix-bc',
    appId: '1:986887862089:android:9421d84a3c52a911264c98',
    messagingSenderId: '986887862089',
    projectId: 'let-s-cook-880bc',
    storageBucket: 'let-s-cook-880bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQm_Q8L4BfLN4d_BjPhiIiBVW686qh98',
    appId: '1:986887862089:ios:e1ed890f3663ce5e264c98',
    messagingSenderId: '986887862089',
    projectId: 'let-s-cook-880bc',
    storageBucket: 'let-s-cook-880bc.appspot.com',
    iosBundleId: 'com.letscook.letsCook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQm_Q8L4BfLN4d_BjPhiIiBVW686qh98',
    appId: '1:986887862089:ios:955ea827aea50d2a264c98',
    messagingSenderId: '986887862089',
    projectId: 'let-s-cook-880bc',
    storageBucket: 'let-s-cook-880bc.appspot.com',
    iosBundleId: 'com.letscook.letsCook.RunnerTests',
  );
}
