name: lets_cook

description: "Let's Cook"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  cloud_firestore: ^4.16.1
  image_picker: ^1.0.7
  google_fonts: ^6.2.0
  firebase_storage: ^11.7.1
  collection: ^1.18.0
  photo_view: ^0.14.0
  google_sign_in: ^6.2.1

dev_dependencies:
  fake_cloud_firestore: ^2.4.9
  firebase_auth_mocks: ^0.13.0
  mockito: ^5.0.15
  network_image_mock: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/playstore.png"
  min_sdk_version: 21




flutter:
  uses-material-design: true
  assets:
    - lib/resources/francesinha.jpg
    - lib/resources/default_userimage.png
    - lib/resources/LetsCookOfc.png
